### ISSUE TITLE
Diagrama de casos de uso

### ISSUE THREAD

**Issue by NuriaMartinez** [saragonzalezbarcena/Tarea2.ProcesoIterativo.GIS#1]
Identificar los actores, casos de uso y sus relaciones.

**Comment by saragonzalezbarcena** [comment]
Ver pdf entregable

**Comment by saragonzalezbarcena** [comment]
![diagrama de casos de uso](https://user-images.githubusercontent.com/80346430/118676459-b5d15000-b7fb-11eb-85b1-b2874e2d6731.PNG)
