### ISSUE TITLE
Catálogo de requisitos funcionales

### ISSUE THREAD

**Issue by saragonzalezbarcena** [saragonzalezbarcena/Tarea2.ProcesoIterativo.GIS#3]

**Comment by NaiaraGadea** [comment]
**Requisito funcional RF-01: Identificar usuario** 

Ver pdf entregable.

**Comment by imb1006** [comment]
**Requisito funcional RF-02: Crear envío**

Ver pdf entregable.

**Comment by NaiaraGadea** [comment]
**Requisito funcional RF-03: Establecer estado del envío**

Ver pdf entregable.

**Comment by imb1006** [comment]
**Requisito funcional RF-04: Registrar llegada**

Ver pdf entregable.
