### ISSUE TITLE
Diagrama de colaboración/secuencia de cada tipo

### ISSUE THREAD

**Issue by saragonzalezbarcena** [saragonzalezbarcena/Tarea2.ProcesoIterativo.GIS#5]

**Comment by NaiaraGadea** [comment]
**Diagrama de secuencia de caso de uso CS-1: Enviar pedido**
Ver pdf entregable

**Comment by imb1006** [comment]
**Diagrama de colaboración de caso de uso CS-2: Generar informe**
Ver pdf entregable

**Comment by NaiaraGadea** [comment]
**Diagrama de secuencia de caso de uso CS-3 y CS-4: Recibir envíos y Validación de código de barras**
Ver pdf entregable

**Comment by imb1006** [comment]
**Diagrama de secuencia de caso de uso CS-5: Generar informe de envíos con incidencias.**
Ver pdf entregable

**Comment by NaiaraGadea** [comment]
**Diagrama de colaboración de caso de uso CS-6: Dar de alta usuario**
Ver pdf entregable

**Comment by imb1006** [comment]
**Diagrama de colaboración de caso de uso CS-7: Dar de alta técnicas analíticas**
Ver pdf entregable

**Comment by NaiaraGadea** [comment]
**Diagrama de colaboración de caso de uso CS-8: Dar de alta facultativos**
Ver pdf entregable
